ForkbombEu/didroom-dashboard

admin/pb_migrations/1688414388_updated_signatures.js
webapp/src/lib/components/signDocumentButton.svelte
webapp/src/routes/api/getDataToSign/+server.ts
webapp/src/routes/api/signDocument/+server.ts
webapp/src/routes/api/validateSignature/+server.ts
webapp/src/routes/my/(protected)/sign/+page.svelte
webapp/src/routes/my/signatures/+page.svelte
webapp/src/routes/my/signatures/signed_document/+page.svelte

- refactor: sign documents from signature table
- refactor: add validate button in signed_document page

refactor: sign document in signatures page and validate result in signed_document page

---

webapp/src/routes/my/+layout.svelte
webapp/src/routes/my/signatures/_partials/SignedFileDisplay.svelte
webapp/src/routes/my/validate/+page.svelte

- feat: initialize validate signature
- feat: make signed file downloadable as json
- fix: link main menu to validate page
- feat: type safe on upload signature file
- refactor: download signed file button

feat: validate signature

---

webapp/src/lib/components/signaturesTableHead.svelte
webapp/src/lib/schema/recordsManager/recordActions/createRecord.svelte
webapp/src/lib/schema/recordsManager/recordActions/editRecord.svelte
webapp/src/lib/schema/recordsManager/views/recordsTable.svelte
webapp/src/routes/my/+layout.svelte
webapp/src/routes/my/folders/+page.svelte
webapp/src/routes/my/signatures/+page.svelte
webapp/src/routes/my/signatures/_partials/Files.svelte
webapp/src/routes/my/signatures/_partials/FolderDisplay.svelte
webapp/src/routes/my/signatures/_partials/Info.svelte
webapp/src/routes/my/signatures/_partials/OwnerDisplay.svelte
webapp/src/routes/my/signatures/_partials/ShareSignature.svelte
webapp/src/routes/my/signatures/_partials/SignedFileDisplay.svelte

- style: mobile layout
- fix: not logout on hover logout button
- fix: topbar user menu
- style: responsive table
closes: #54 
closes: #56 
closes: #58

style: mobile layout

---

webapp/src/lib/layout/SidebarLinks.svelte
webapp/src/routes/my/+layout.svelte
webapp/src/routes/my/services/+page.svelte
webapp/src/routes/my/sidebarLinks.ts

- style: apply new starter layout to /my section
- fix: disabled links
- fix: did url

style: apply new starter layout in /my pages

---

webapp/src/hooks.client.ts

fix: login on safari

---

admin/pb_migrations/1706279441_updated_templates.js
admin/pb_migrations/1706279519_updated_services.js
webapp/src/routes/my/organizations/[id]/+layout.svelte
webapp/src/routes/my/organizations/[id]/services/[serviceId]/+page.svelte
webapp/src/routes/my/organizations/[id]/services/_partials/serviceForm.svelte

- removed `credential_type` field from `template` collection
- added it to `service` collection
- added `sd-jwt` option

feat: Add `credential_type` field to `service` collection, add `sd-jwt`

---

admin/pb_migrations/1708588395_created_coconut_credential_issuers.js
admin/pb_migrations/1708588862_updated_coconut_credential_issuers.js
admin/pb_migrations/1708590798_created_multisignatures.js
admin/pb_migrations/1708590817_updated_multisignatures.js
admin/pb_migrations/1708591014_created_multisignature_requests.js
admin/pb_migrations/1708591551_updated_multisignature_requests.js
admin/pb_migrations/1708591652_updated_multisignatures.js
admin/pb_migrations/1708592026_updated_multisignatures.js
admin/pb_migrations/1708593530_updated_multisignatures.js
admin/pb_migrations/1708593678_updated_multisignatures.js
admin/pb_migrations/1708594225_updated_multisignature_requests.js
admin/pb_migrations/1708594381_updated_multisignature_requests.js
admin/pb_migrations/1708603834_updated_multisignatures.js
admin/pb_migrations/1708604419_updated_multisignature_requests.js
admin/pb_migrations/1708604443_updated_multisignatures.js
admin/pb_migrations/1708605097_updated_multisignature_seals.js
admin/pb_migrations/1708610301_updated_multisignature_seals.js
admin/pb_migrations/1708610316_updated_multisignatures.js
admin/pb_migrations/1708610397_updated_multisignature_seals.js
admin/pb_migrations/1708610516_updated_multisignatures.js
admin/pb_migrations/1708610724_updated_multisignature_seals.js
webapp/src/lib/collectionManager/ui/collectionManagerHeader.svelte
webapp/src/routes/my/_partials/sidebarLinks.ts
webapp/src/routes/my/multisignatures/+page.svelte
webapp/src/routes/my/multisignatures/requests/+page.svelte
webapp/src/routes/my/organizations/[id]/issuers/+page.svelte

added collections:
- `coconut_credential_issuers`
- `multisignatures`
- `multisignatures_requests`

feat: Multisignatures setup

---

webapp/src/routes/[[lang]]/my/organizations/[id]/services/[serviceId]/+page.svelte

according to
https://github.com/ForkbombEu/wallet/issues/194

feat: update issuance QR generation

---

admin/did/did.go

Reverts ForkbombEu/signroom#472

Revert "fix: did api should return same object if generate a new one or retrive an old one"

---

webapp/src/routes/[[lang]]/my/organizations/[id]/credential-issuances/[issuance_id]/+layout.ts
webapp/src/routes/[[lang]]/my/organizations/[id]/credential-issuances/[issuance_id]/+page.svelte
webapp/src/routes/api/downloadCredentialIssuer/+server.ts
webapp/src/routes/api/downloadCredentialIssuer/index.ts

feat(api): add scopes_supported when downloading microservices

---

admin/pb_migrations/1713447871_updated_templates.js
admin/pb_migrations/1713447927_created_templates_public.js
admin/pb_migrations/1713447939_updated_templates_public.js
admin/pb_migrations/1713447963_updated_templates_public.js
admin/pb_migrations/1713448003_updated_templates_public.js
admin/pb_migrations/1713448040_updated_templates_public.js
admin/pb_migrations/1713448110_updated_templates_public.js
admin/pb_migrations/1713449170_updated_templates.js
admin/pb_migrations/1713449241_updated_templates_public_data.js
webapp/src/lib/components/organizationTabs.svelte
webapp/src/lib/rbac/index.ts
webapp/src/lib/utils/organizations.ts
webapp/src/routes/[[lang]]/my/+layout.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/credential-issuances/+page.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/+page.ts
webapp/src/routes/[[lang]]/my/organizations/[id]/verification-flows/+page.svelte

- templates collection is now available only to organization admin and owner
- templates page in organizations is hidden (also from the rest of the ui)
- `templates_public_data` collection is available for everyone

feat: templates public data

---

webapp/src/routes/[[lang]]/my/organizations/[id]/credential-issuances/[issuance_id]/+page.svelte

fix wallet link instead of verifier

fix: Update +page.svelte

---

webapp/src/routes/[[lang]]/my/+layout.svelte

feat: add version number

---

webapp/messages/en.json
webapp/src/lib/recordForm/recordForm.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/credential-issuances/_partials/serviceForm.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/+page.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/_partials/templateForm.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/verification-flows/_partials/verificationFlowForm.svelte

feat(forms): add cancel buttons

---

webapp/src/routes/api/download-microservices/credential-issuer.ts
webapp/src/routes/api/download-microservices/utils/credential-subject.ts

fix(microservices): credential_configurations_supported is a dictionary

---

webapp/src/lib/certificates/autosigned-certificate.ts
webapp/src/routes/[[lang]]/my/certificates/+page.svelte
webapp/src/routes/[[lang]]/my/certificates/_partials/autosignedCertificateForm.svelte
webapp/src/routes/[[lang]]/my/certificates/_partials/certificateView.svelte

* add name into the PEM cert
* allow to download certs
* allow to copy and get private key
closes #883

feat: improve x509 certs usability

---

admin/pb_hooks/didroom_notifications.pb.js
admin/pb_hooks/features.pb.js
admin/pb_hooks/flows.pb.js
admin/pb_hooks/utils.js
webapp/src/routes/[[lang]]/my/organizations/[id]/credential-issuances/_partials/serviceForm.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/credential-issuances/create/+page.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/verification-flows/_partials/verificationFlowForm.svelte
webapp/tests/logged/issuance-flow.spec.ts

- improved checks for `didroom_notifications` hooks
- improved checks for admin context in various hooks
- protecting `public` and `api_available` fields in flows collections
- changed uppercase handling in slug creation

feat(flows): improved forms and hooks handling

---

webapp/src/lib/certificates/autosigned-certificate.ts
webapp/src/lib/certificates/parse.ts
webapp/src/lib/certificates/strings.ts
webapp/src/lib/certificates/types.ts
webapp/src/lib/certificates/utils.ts
webapp/src/routes/[[lang]]/my/certificates/_partials/autosignedCertificateForm.svelte

- fix: first part of fixes to certificate upload
- fix: add checks also for RSA certificate and sk
- feat: add did as SubjectAlternativeName extension inside the autosigned certificate

feat: improve cheks during certificate upload and add did in autosigned certificate

---

admin/pb_migrations/1758543106_updated_templates.js
admin/pb_migrations/1758543138_updated_templates.js
admin/pb_migrations/1758815865_updated_templates.js
admin/pb_migrations/1758815865_updated_templates_public_data.js
webapp/messages/en.json
webapp/src/lib/components/records/recordSearch.svelte
webapp/src/lib/components/records/recordSelect.svelte
webapp/src/lib/components/records/recordsManager.svelte
webapp/src/lib/components/records/types.ts
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/+page.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/_partials/claims-editor.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/_partials/claims.ts
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/_partials/dcql.ts
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/_partials/templateForm.svelte

- **chore(templates): set drawer with to 75%**
- **feat: create releations between issuance flow and verification_template**
- **fix: initial rendering of dcql_query**

feat: simplify creation of dcql_query

---

webapp/src/routes/[[lang]]/my/organizations/[id]/settings/+page.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/+page.svelte

fix: rebuild pages when orgnization id changes

---

webapp/package.json
webapp/pnpm-lock.yaml
webapp/src/lib/components/code-display.svelte
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/_partials/dcql.ts
webapp/src/routes/[[lang]]/my/organizations/[id]/templates/_partials/templateForm.svelte

add also the issuer value to the list of claims and make the dcql query box not modifiable

fix(verification_template): show issuance_flow that are public or the ones in the org that I am a member of
